language: node_js
node_js:
 - "10.17.0"
branches:
  only:
    - master
    - staging
before_deploy:
  - node ./scripts/create-buckets.js halloween19-staging.dbknews.com halloween19.dbknews.com
  - npm run build
deploy:
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    bucket: "halloween19.dbknews.com"
    acl: public_read
    local_dir: build
    skip_cleanup: true
    on:
      branch: master
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    bucket: "halloween19-staging.dbknews.com"
    acl: public_read
    local_dir: build
    skip_cleanup: true
    on:
      branch: staging
after_deploy:
  - echo "Static site deployed"
